const BASE_HORIZONTAL_MARGIN = 24.0;

const LOGIN_SCREEN_HEIGHT = 750.0;

const TITLE_TEXT_FONT_SIZE = 20.0;
const BODY3_TEXT_FONT_SIZE = 15.0;
const CAPTION_SMALLER_TEXT_FONT_SIZE = 12.0;
const MICRO_TEXT_FONT_SIZE = 6.0;
const MEDIUM_TEXT_FONT_SIZE = 22.0;
const LARGE_TEXT_FONT_SIZE = 24.0;
const VERY_LARGE_TEXT_FONT_SIZE = 34.0;
const LARGE_X_TEXT_FONT_SIZE = 32.0;
const VERY_SMALL_TEXT_FONT_SIZE = 10.0;

const HEADLINE1_TEXT_FONT_SIZE = 30.0;
const HEADLINE2_TEXT_FONT_SIZE = 14.0;
const HEADLINE3_TEXT_FONT_SIZE = 18.0;
const HEADLINE4_TEXT_FONT_SIZE = 14.0;
const SUBTITLE1_TEXT_FONT_SIZE = 18.0;
const SUBTITLE2_TEXT_FONT_SIZE = 18.0;
const CAPTION_TEXT_FONT_SIZE = 12.0;
const BUTTON_TEXT_FONT_SIZE =18.0;

const COMMON_BUTTON_RADIUS = 5.0;
const COMMON_BUTTON_HEIGHT = 50.0;
const TEXT_FORM_FIELD_SUFFIX_ICON = 18.0;
const COMMON_FORM_BOTTOM_SPACE = 50.0;
const COMMON_LIST_BOTTOM_SPACE = 30.0;
const DEFAULT_BOTTOM_BAR_RADIUS = 25.0;

const COMMON_DIVIDER_THICKNESS = 1.0;

const COMMON_BORDER_RADIUS = 6.0;

const LARGER_DIVIDER_THICKNESS = 8.0;

const DEFAULT_SCREEN_LEFT_RIGHT_MARGIN = 30.0;
const DEFAULT_SCREEN_LEFT_RIGHT_MARGIN2 = 15.0;
const DEFAULT_RIGHT_MARGIN = 30.0;
const DEFAULT_APPBAR_TOP_MARGIN = 20.0;
const DEFAULT_APPBAR_BOTTOM_MARGIN = 20.0;
const DEFAULT_APPBAR_NOTIFICATION_TOP_MARGIN = 20.0;
const DEFAULT_APPBAR_NOTIFICATION_RIGHT_MARGIN = 20.0;

const DEFAULT2_LEFT_MARGIN = 15.0;
const DEFAULT2_RIGHT_MARGIN = 15.0;

const DEFAULT_LIST_SPACING = 25.0;
const DEFAULT_SCREEN_RADIUS = 30.0;
const DEFAULT_BOTTOM_SHEET_RADIUS = 20.0;
const DEFAULT_APP_BAR_HEIGHT = 60.0;
const DEFAULT_APP_BAR_HEIGHT_2X = 140.0;

const BOTTOM_BAR_OPTION_HEIGHT = 20.0;
const BOTTOM_BAR_OPTION_WIDTH = 20.0;

const COMMON_TOP_LOGO_MARGIN = 100.0;

const HEADLINE5_TEXT_FONT_SIZE = 20.0;
const BODY1_TEXT_FONT_SIZE = 18.0;
const BODY2_TEXT_FONT_SIZE = 18.0;
const DEFAULT_HEIGHT_BETWEEN_WIDGET = 18.0;