// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzrf4FJWble-hewGLVIiUWt1RB1lI2vYs',
    appId: '1:1013573145835:web:b97906006b02ee4a811aae',
    messagingSenderId: '1013573145835',
    projectId: 'e-office-desk-flutter',
    authDomain: 'e-office-desk-flutter.firebaseapp.com',
    storageBucket: 'e-office-desk-flutter.appspot.com',
    measurementId: 'G-69Z9FKN9NK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHMV5A4Dz0iEJGMAoYPfu5a3odBNXttV8',
    appId: '1:1013573145835:android:e0bfa3a6c8bf2f9c811aae',
    messagingSenderId: '1013573145835',
    projectId: 'e-office-desk-flutter',
    storageBucket: 'e-office-desk-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDxd-MjEbcWuyncvt78M4wA_YFK5aSMcM',
    appId: '1:1013573145835:ios:850a068a24fdabe7811aae',
    messagingSenderId: '1013573145835',
    projectId: 'e-office-desk-flutter',
    storageBucket: 'e-office-desk-flutter.appspot.com',
    iosClientId: '1013573145835-jucs16ektajtgk9b9grg4ismqgf3vspl.apps.googleusercontent.com',
    iosBundleId: 'com.sharvayainfotech.eofficedesk',
  );
}
